# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='deadline')),
                ('caption', models.CharField(max_length=30)),
                ('second_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtd.SecondClass')),
            ],
        ),
        migrations.CreateModel(
            name='TopClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='top_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtd.TopClass'),
        ),
        migrations.AddField(
            model_name='secondclass',
            name='top_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtd.TopClass'),
        ),
    ]
