# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='caption',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
