# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0003_auto_20171109_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='caption',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='topclass',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
