# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0004_auto_20171109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='second_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gtd.SecondClass'),
        ),
        migrations.AlterField(
            model_name='task',
            name='top_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gtd.TopClass'),
        ),
    ]
