# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtd', '0005_auto_20171110_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(verbose_name='deadline'),
        ),
    ]
