# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170922_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.ManyToManyField(db_constraint=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
